# sudo loadkeys si
xmodmap ~/.config/zsh/.xmodmaprc
xcape -e '#66=Escape'

# Profile file. Runs on login. Environmental variables are set here.

# Default programs:
export EDITOR="nvim"
export BROWSER="firefox"

# ~/ Clean up:
export ZDOTDIR="$HOME/.config/zsh"
