# sudo loadkeys si
# xmodmap ~/.config/zsh/.xmodmaprc
# xcape -e '#66=Escape'

export PATH=/home/david/pear/bin:$PATH

setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape' -t 175

# makin si keyboard layout
setxkbmap -layout si

# Profile file. Runs on login. Environmental variables are set here.

# Default programs:
export EDITOR="nvim"
export BROWSER="firefox"

# ~/ Clean up:
export ZDOTDIR="$HOME/.config/zsh"


#. "$HOME/.cargo/env"
